import json

from personal_wiki.backends.fake import FakeBackend
from personal_wiki.config import NOTE_TEXT_BUDGET, PLAN_OUTLINE_BUDGET
from personal_wiki.ingest import run_ingest
from personal_wiki.vault import list_notes, read_note, resolve_links, validate_title, write_note


def note_files(vault):
    return sorted(p.relative_to(vault).as_posix() for p in (vault / "wiki").rglob("*.md"))


def test_ingest_creates_notes_with_valid_names(fake_settings, fake_backend):
    log = run_ingest(fake_settings, fake_backend, [])
    assert log["totals"]["ingested"] == 2 and log["totals"]["notes_written"] >= 2
    notes = list_notes(fake_settings.vault)
    assert notes
    for n in notes:
        assert validate_title(n.title)[0], n.title
        assert n.path.stem == n.title == n.frontmatter["title"]
        assert n.body.startswith(f"# {n.title}\n")
        assert n.folder in ("Projects", "Concepts", "Course")
        for key in ("source_id", "source_sha256", "sections_used", "created", "updated", "reviewed", "generated_by", "note_id"):
            assert key in n.frontmatter, key
        assert "## Sources" in n.body and "[[wiki/Sources/" in n.body
    assert (fake_settings.vault / "index.md").exists()
    assert (fake_settings.vault / "wiki/Sources/Garden Sensor Log.md").exists()
    assert (fake_settings.vault / "wiki/Sources/Bike Commute Notes.md").exists()
    assert (fake_settings.run_dir / "ingest/ingest_log.json").exists() and (fake_settings.run_dir / "ingest/ingest_log.md").exists()
    assert list((fake_settings.run_dir / "ingest/calls").glob("*.json"))


def test_ingest_idempotent(fake_settings, fake_backend):
    run_ingest(fake_settings, fake_backend, [])
    before = {f: (fake_settings.vault / f).read_text() for f in note_files(fake_settings.vault)}
    index_before = (fake_settings.vault / "index.md").read_text()
    log = run_ingest(fake_settings, fake_backend, [])
    assert all(s["action"] == "up-to-date" for s in log["sources"])
    assert log["totals"]["calls"] == 0
    assert log["log_file"] == "ingest/ingest_log-2.json"
    assert (fake_settings.run_dir / "ingest/ingest_log.json").exists() and (fake_settings.run_dir / "ingest/ingest_log-2.json").exists()
    after = {f: (fake_settings.vault / f).read_text() for f in note_files(fake_settings.vault)}
    assert set(before) == set(after)
    for f in before:
        if not f.startswith("wiki/Sources/"):
            assert before[f] == after[f], f
    strip = lambda t: "\n".join(l for l in t.split("\n") if "regenerated by" not in l)
    assert strip(index_before) == strip((fake_settings.vault / "index.md").read_text())


def test_changed_source_rewrites_same_filenames(fake_settings, fake_backend):
    run_ingest(fake_settings, fake_backend, [])
    src = fake_settings.vault / "raw/Garden Sensor Log.md"
    garden_before = {n.path: n.frontmatter for n in list_notes(fake_settings.vault) if n.frontmatter["source_id"] == "garden-sensor-log"}
    src.write_text(src.read_text() + "\n\nA new paragraph about the pump timer added later.\n")
    log = run_ingest(fake_settings, fake_backend, [])
    actions = {s["source"]: s["action"] for s in log["sources"]}
    assert actions["raw/Garden Sensor Log.md"] == "ingested" and actions["raw/Bike Commute Notes.md"] == "up-to-date"
    garden_after = {n.path: n.frontmatter for n in list_notes(fake_settings.vault) if n.frontmatter["source_id"] == "garden-sensor-log"}
    assert set(garden_before) == set(garden_after)
    for path, fm in garden_after.items():
        assert fm["source_sha256"] != garden_before[path]["source_sha256"]
        assert fm["created"] == garden_before[path]["created"]


def test_reviewed_note_protected(fake_settings, fake_backend):
    run_ingest(fake_settings, fake_backend, [])
    note = next(n for n in list_notes(fake_settings.vault) if n.frontmatter["source_id"] == "garden-sensor-log")
    fm = dict(note.frontmatter)
    fm["reviewed"] = True
    body = note.body.replace("## Summary\n\n", "## Summary\n\nREVIEWED SENTENCE KEPT. ", 1)
    write_note(note.path, fm, body)
    src = fake_settings.vault / "raw/Garden Sensor Log.md"
    src.write_text(src.read_text() + "\n\nAnother change.\n")
    log = run_ingest(fake_settings, fake_backend, [])
    kept = read_note(note.path)
    assert kept.frontmatter["reviewed"] is True and "REVIEWED SENTENCE KEPT." in kept.body
    drafts = list((fake_settings.run_dir / "ingest/drafts").rglob("*.md"))
    assert any(d.stem == note.title for d in drafts)
    assert note.title in next(s for s in log["sources"] if s["source_id"] == "garden-sensor-log")["notes_drafted"]
    run_ingest(fake_settings, fake_backend, [], force=True, overwrite_reviewed=True)
    assert read_note(note.path).frontmatter["reviewed"] is False


def test_unsupported_extension_reported(fake_settings, fake_backend):
    (fake_settings.vault / "raw/notes.pdf").write_bytes(b"%PDF-1.4 fake")
    log = run_ingest(fake_settings, fake_backend, [])
    entry = next(s for s in log["sources"] if s["source"] == "raw/notes.pdf")
    assert entry["action"] == "unsupported" and ".md and .txt" in entry["message"]


def test_plan_validation_and_fallback(fake_settings):
    class BadPlan(FakeBackend):
        def generate(self, messages, *, kind, **kw):
            c = super().generate(messages, kind=kind, **kw)
            if kind == "plan":
                c.text = "I cannot plan this."
            return c

    log = run_ingest(fake_settings, BadPlan(), [])
    assert all(s["plan_origin"] == "heuristic" for s in log["sources"])
    for n in list_notes(fake_settings.vault):
        assert validate_title(n.title)[0]
    assert all(s["calls"][0]["attempt"] == 1 and s["calls"][1]["attempt"] == 2 for s in log["sources"])


def test_title_collision_across_sources(fake_settings):
    class SameTitle(FakeBackend):
        def _plan(self, user, messages):
            plan = json.loads(super()._plan(user, messages))
            plan["notes"][0]["title"] = "Shared Title Note"
            return json.dumps(plan)

    run_ingest(fake_settings, SameTitle(), [])
    titles = [n.title for n in list_notes(fake_settings.vault)]
    shared = [t for t in titles if t.startswith("Shared Title Note")]
    assert len(shared) == 2 and len(set(shared)) == 2
    owners = {n.title: n.frontmatter["source_id"] for n in list_notes(fake_settings.vault) if n.title in shared}
    assert len(set(owners.values())) == 2


def test_links_only_to_existing_or_planned(fake_settings, fake_backend):
    run_ingest(fake_settings, fake_backend, [])
    for n in list_notes(fake_settings.vault, include_sources=True):
        resolved, dangling = resolve_links(fake_settings.vault, n.body)
        assert dangling == [], (n.title, dangling)
    text = (fake_settings.vault / "index.md").read_text()
    assert resolve_links(fake_settings.vault, text)[1] == []


def test_call_log_budget_fields(fake_settings, fake_backend):
    log = run_ingest(fake_settings, fake_backend, [])
    for s in log["sources"]:
        for c in s["calls"]:
            limit = PLAN_OUTLINE_BUDGET if c["kind"] == "plan" else NOTE_TEXT_BUDGET
            assert c["payload_chars"] <= limit + 200
            assert c["payload_capped"] is False
            assert c["dump_file"].startswith("ingest/calls/") and (fake_settings.run_dir / c["dump_file"]).exists()
    assert log["budgets"]["note_text_chars"] == NOTE_TEXT_BUDGET
